name: Build Argilla package

on:
  workflow_call:

jobs:
  build:
    name: Build the python package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build Package 🍟
        run: |
          pip install -U build
          scripts/build_distribution.sh

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: dist
