name: Deploy Argilla environment

on:
  workflow_call:
    inputs:
      service-name:
        description: The name of the service deployed in Cloud Run
        type: string
      docker-image:
        description: The name of the Docker image to deploy.
        type: string

jobs:
  deploy:
    name: Deploy Argilla to Cloud Run
    runs-on: ubuntu-latest

    # Grant permissions to `GITHUB_TOKEN` for Google Cloud Workload Identity Provider
    permissions:
      contents: read
      id-token: write

    steps:
      # Authenticate in GCP using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WIP }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
          flags: --no-cpu-throttling

      - name: Deploy in Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ inputs.service-name }}
          image: ${{ inputs.docker-image }}

      - name: echo url
        run: 'echo "${{ steps.deploy.outputs.url }}"'
