name: Deploy Argilla environment

on:
  workflow_call:
    inputs:
      image-name:
        description: The name of the Docker image to deploy.
        type: string
      image-version:
        description: The version of the Docker image to deploy.
        type: string

jobs:
  deploy:
    name: Deploy Argilla to Cloud Run
    runs-on: ubuntu-latest

    # Grant permissions to `GITHUB_TOKEN` for Google Cloud Workload Identity Provider
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      # Authenticate in GCP using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WIP }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}

      - name: Deploy in Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: argilla-quickstart-${{ inputs.image-version }}
          image: europe-docker.pkg.dev/argilla-ci/${{ inputs.image-name}}:${{ inputs.image-version }}
          region: europe-southwest1
          flags: '--min-instances=1 --max-instances=1 --port=6900 --cpu=2000m --memory=2048Mi --no-cpu-throttling'

      - name: Display Cloud Run URL
        run: 'echo "URL: ${{ steps.deploy.outputs.url }}"'

      - name: Comment PR with Cloud Run URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            The URL of the deployed environment for this PR is ${{ steps.deploy.outputs.url }}
          comment_tag: cloud_run_url
          reactions: rocket
