name: Deploy Argilla environment

on:
  workflow_call:
    inputs:
      image-name:
        description: The name of the Docker image to deploy.
        type: string
      image-version:
        description: The version of the Docker image to deploy.
        type: string

jobs:
  deploy:
    name: Deploy Argilla to Cloud Run
    runs-on: ubuntu-latest

    # Grant permissions to `GITHUB_TOKEN` for Google Cloud Workload Identity Provider
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      # Authenticate in GCP using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WIP }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
          flags: --no-cpu-throttling

      - name: Deploy in Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: argilla-quickstart-${{ inputs.image-version }}
          image: europe-docker.pkg.dev/argilla-ci/${{ inputs.image-name}}:${{ inputs.image-version }}
          region: europe-southwest1
          flags: '--no-cpu-throttling --min-instances 1 --max-instances 1'

      - name: Display Cloud Run URL
        run: 'echo "URL: ${{ steps.deploy.outputs.url }}"'

      - name: Comment PR with Cloud Run URL
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          message: |
            The URL of the deployed environment for this PR is '${{ steps.deploy.outputs.url }}'
          comment_tag: cloud_run_url
          reactions: rocket
